### ISSUE TITLE
Talk to customers about threads usage

### ISSUE THREAD

**Issue by dazuck** [3box/3box#505] opened 2019-02-27 14:42 UTC
Conduct customer interviews to understand their requirements. 
Gather general feedback and input, and particular focus on refining our threads requirements.

**Comment by oed** [comment] 2019-02-27 14:51
Duplicate of #498

**Comment by mattlockyer** [comment] 2019-03-06 15:26
Hey y'all. I'm still going to reach out and survey teams this week / weekend on what they want from a threads feature v1.

I'm thinking Google Form / Email with teams Thursday Friday as a I reach out? Suggestions?

Hope to codify and translate this to a rough spec next week.

**Comment by mattlockyer** [comment] 2019-03-11 04:39
Hey @dazuck @michaelsena @oed @zachferland I've created a form here:
https://docs.google.com/forms/d/1J5uxuBWPFW0W4EYALMPNfZosDGGFjc8YqfstcAJSL3M/edit?usp=sharing

Wondering if you could take a look? Go ahead and edit language directly. I'll spruce up the graphics and get it out to projects this week.

It's going to be highly qualitative, so I'll have to codify it after and loop someone in to take their own pass to eliminate any bias.

**Comment by oed** [comment] 2019-03-11 07:12
@mattlockyer ty, but I don't have permissions to view :)

**Comment by dazuck** [comment] 2019-03-11 14:00
@mattlockyer let's discuss in growth meeting. Before making detailed comments it would be helpful to hear the goals of this survey. It's more big-picture than I envisioned, which may well be the right approach. Would just like to understand how this fits alongside other efforts.

**Comment by michaelsena** [comment] 2019-03-11 14:15
@mattlockyer quick comment is that threads are not only a meta discussion layer for on-chain things and most of the survey is about that... they're also a way to comment on objects/posts/etc in apps generally, such as a The Block article, stored on their server, but the comments are decentralized and off-chain. Would like to see some of that baked in here.

**Comment by michaelsena** [comment] 2019-03-11 14:17
Etherscan and Gitcoin have implemented Disqus, which is so sad.
Etherscan for on-chain stuff like addresses, contracts, txs...
Gitcoin for Kudos, etc.
We can serve those sure, but also for comments on media publications, and p2p chats in apps...

**Comment by mattlockyer** [comment] 2019-03-12 14:42
Hey All, refreshed the survey here:
https://docs.google.com/forms/d/1J5uxuBWPFW0W4EYALMPNfZosDGGFjc8YqfstcAJSL3M/edit

I think removes the on-chain constraint and helps guide people to discuss the features we were discussing yesterday without leading them too much.

**Closed** 2022-01-12 15:49 UTC
Labels: Customer Development
