### ISSUE TITLE
Can't reopen the same box with identity wallet if local ipfs has been cleared

### ISSUE THREAD

**Issue by msterle** [3box/3box#941] opened 2020-02-18 11:51 UTC
Steps to reproduce:

1. Create a new npm package
2. `npm i 3boc identity-wallet`
3. create index.js with the following:
    ```
    const Box = require('3box')
    const IdentityWallet = require('identity-wallet')

    async function start() {
      const SEED = '0x95838ece1ac686bde68823b21ce9f564bc536abbb9c3500fa6da81f17086a6aa'
      const idWallet = new IdentityWallet(() => true, { seed: SEED })
      const provider = idWallet.get3idProvider()
      const box = await Box.openBox(null, provider)
      console.log('Box opened')
      box.logout()
    }

    start()
    ```

4. force-quit (client doesn't halt otherwise)
5. remove local ipfs and orbit directories with `rm -fr ipfs orbitdb`
6. rerun index.js

**Comment by oed** [comment] 2020-02-20 12:09
Might be related to: https://github.com/3box/identity-wallet-js/issues/34

**Comment by zachferland** [comment] 2020-03-11 19:53
@oed forgot what you mentioned before, but yeah looks this is partially resolved by pinning auth data (so won't work for this seed here now, but will for another), don't see where/when that fix was 

still needs another fix, when not stored locally, takes two opens, before it resolves on second open

**Comment by oed** [comment] 2020-03-11 20:01
@zachferland why wasn't the authData pinned?

**Comment by zachferland** [comment] 2020-03-11 20:08
@oed couldn't remember if you mentioned that, because yeah i dont see where that would have been true

**Comment by oed** [comment] 2020-03-11 20:17
That's very strange because I explicitly did a patch that fixed this.

**Comment by zachferland** [comment] 2020-03-11 20:19
ok where is that path?  couldnt find it

so yes seems like it is definitely pinning now, and it partially fixed it, since mike last tried it, now just not resolving on first open, but works on second

**Comment by oed** [comment] 2020-03-11 20:20
Looks like it is actually pinning: https://github.com/3box/3box-pinning-node/blob/develop/src/pinning.js#L316

**Comment by zachferland** [comment] 2020-03-13 14:55
@msterle - using your example above, it now works in the following case, have existing (used) seed, clear orbit/ipfs, run (it hangs before completing open, probs needs few seconds to get data), exit, run again and now it will work

**Comment by msterle** [comment] 2020-03-13 14:59
@zachferland can this be done programmatically (without user intervention)?

**Comment by zachferland** [comment] 2020-03-13 15:01
It appears this is the root issue - https://github.com/ipfs/js-ipfs-bitswap/pull/214

When having to fetch same data/cid from concurrently it just hangs. This seems to happen most frequently with the did docs, as this is used to verify identity on entires and other verifications, ends up having dag.get called concurrently at some point. Might be able to limit this, and can also fix in other ways, probably in 3id resolver, but having that fixed in ipfs would be helpful. 

Saw same issue in past it looks like, and may or may not be primarily because of did doc. https://github.com/3box/3box-pinning-node/issues/288 But was causing random test failures.

**Comment by zachferland** [comment] 2020-03-13 15:11
@msterle if within same process, i guess not,  maybe can spawn child process, exit after few seconds, then run again. 

I can look at your code as well if you dont have time today, i think either way may be short term hacky somewhere since not sure i will want to change any production to get around it. But can look at quick fix in 3id resolver, and that branch can be pulled in for tests at least. But may still show up in other ways.

**Comment by zachferland** [comment] 2020-03-13 17:05
Ok since almost only caused by did doc it appears, easy enough to circumvent in ipfs-did-document with cache to not call dag.get multiple times. So will push that up soon

**Comment by zachferland** [comment] 2020-03-13 18:17
@msterle you can now 'npm i github:3box/js-ipfs-did-document#feat/diddoc-cache' and this should be fixed for you for now

**Comment by msterle** [comment] 2020-03-16 12:44
Thanks @zachferland, I tried some of the functional tests and they seem to be working now :)

**Closed** 2020-03-24 13:53 UTC
Labels: bug
